Not Found: /api/v1/users/
"GET /api/v1/users/ HTTP/1.1" 404 7069
Internal Server Error: /api/users/
Traceback (most recent call last):
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\serializers.py", line 479, in to_internal_value
    for field in fields:
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\serializers.py", line 362, in _writable_fields
    for field in self.fields.values():
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\serializers.py", line 1051, in get_fields
    info = model_meta.get_field_info(model)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\utils\model_meta.py", line 39, in get_field_info
    forward_relations = _get_forward_relationships(opts)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\utils\model_meta.py", line 96, in _get_forward_relationships
    not field.remote_field.through._meta.auto_created
AttributeError: 'NoneType' object has no attribute '_meta'
"POST /api/users/ HTTP/1.1" 500 133130
Internal Server Error: /api/users/
Traceback (most recent call last):
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\serializers.py", line 479, in to_internal_value
    for field in fields:
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\serializers.py", line 362, in _writable_fields
    for field in self.fields.values():
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\serializers.py", line 1051, in get_fields
    info = model_meta.get_field_info(model)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\utils\model_meta.py", line 39, in get_field_info
    forward_relations = _get_forward_relationships(opts)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\utils\model_meta.py", line 96, in _get_forward_relationships
    not field.remote_field.through._meta.auto_created
AttributeError: 'NoneType' object has no attribute '_meta'
"POST /api/users/ HTTP/1.1" 500 133136
Internal Server Error: /api/users/
Traceback (most recent call last):
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\serializers.py", line 479, in to_internal_value
    for field in fields:
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\serializers.py", line 362, in _writable_fields
    for field in self.fields.values():
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\serializers.py", line 1051, in get_fields
    info = model_meta.get_field_info(model)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\utils\model_meta.py", line 39, in get_field_info
    forward_relations = _get_forward_relationships(opts)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\utils\model_meta.py", line 96, in _get_forward_relationships
    not field.remote_field.through._meta.auto_created
AttributeError: 'NoneType' object has no attribute '_meta'
"POST /api/users/ HTTP/1.1" 500 133136
Bad Request: /api/users/
"POST /api/users/ HTTP/1.1" 400 236
Bad Request: /api/users/
"POST /api/users/ HTTP/1.1" 400 37
Not Found: /api/interest/
"POST /api/interest/ HTTP/1.1" 404 7070
Bad Request: /api/interestrates/
"POST /api/interestrates/ HTTP/1.1" 400 36
Bad Request: /api/interestrates/
"POST /api/interestrates/ HTTP/1.1" 400 32
Bad Request: /api/loans/
"POST /api/loans/ HTTP/1.1" 400 157
Bad Request: /api/clients/
"POST /api/clients/ HTTP/1.1" 400 196
Bad Request: /api/loans/
"POST /api/loans/ HTTP/1.1" 400 56
Internal Server Error: /api/loans/
Traceback (most recent call last):
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1823, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'Clients'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\serializers.py", line 429, in run_validation
    value = self.validate(value)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\api\serializers\loans.py", line 11, in validate
    if Clients.objects.filter(id=attrs['client']) == None:
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\sql\query.py", line 1393, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\sql\query.py", line 1412, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\sql\query.py", line 1347, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\sql\query.py", line 1193, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\lookups.py", line 77, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1825, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <Clients: cletuss ngwerume>.
"POST /api/loans/ HTTP/1.1" 500 168182
Internal Server Error: /api/loans/
Traceback (most recent call last):
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\serializers.py", line 429, in run_validation
    value = self.validate(value)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\api\serializers\loans.py", line 13, in validate
    if Clients.objects.get(attrs['client']) == None:
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\query.py", line 424, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\sql\query.py", line 1393, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\sql\query.py", line 1412, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\sql\query.py", line 1283, in build_filter
    arg, value = filter_expr
TypeError: cannot unpack non-iterable Clients object
"POST /api/loans/ HTTP/1.1" 500 147491
Internal Server Error: /api/loans/
Traceback (most recent call last):
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\serializers.py", line 429, in run_validation
    value = self.validate(value)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\api\serializers\loans.py", line 13, in validate
    if Clients.objects.get(attrs['client']):
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\query.py", line 424, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\sql\query.py", line 1393, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\sql\query.py", line 1412, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\sql\query.py", line 1283, in build_filter
    arg, value = filter_expr
TypeError: cannot unpack non-iterable Clients object
"POST /api/loans/ HTTP/1.1" 500 147475
Internal Server Error: /api/loans/
Traceback (most recent call last):
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\api\serializers\loans.py", line 18, in create
    days = (validated_data['repayment_date'] - validated_data['date']).days
KeyError: 'repayment_date'
"POST /api/loans/ HTTP/1.1" 500 110464
Bad Request: /api/loans/
"POST /api/loans/ HTTP/1.1" 400 46
Bad Request: /api/loans/
"POST /api/loans/ HTTP/1.1" 400 61
Internal Server Error: /api/loans/
Traceback (most recent call last):
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\api\serializers\loans.py", line 22, in create
    days = (validated_data['repayment_date'] - validated_data['date']).days
KeyError: 'date'
"POST /api/loans/ HTTP/1.1" 500 111500
Internal Server Error: /api/loans/
Traceback (most recent call last):
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\api\serializers\loans.py", line 22, in create
    days = (validated_data['repayment_date'] - datetime.now()).days
TypeError: unsupported operand type(s) for -: 'datetime.date' and 'datetime.datetime'
"POST /api/loans/ HTTP/1.1" 500 111976
Internal Server Error: /api/loans/
Traceback (most recent call last):
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\api\serializers\loans.py", line 22, in create
    days = (validated_data['repayment_date'] - datetime.now().date).days
TypeError: unsupported operand type(s) for -: 'datetime.date' and 'builtin_function_or_method'
"POST /api/loans/ HTTP/1.1" 500 112040
Internal Server Error: /api/loans/
Traceback (most recent call last):
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\api\serializers\loans.py", line 22, in create
    days = (validated_data['repayment_date'] - datetime.now().date).days
TypeError: unsupported operand type(s) for -: 'datetime.date' and 'builtin_function_or_method'
"POST /api/loans/ HTTP/1.1" 500 112040
Internal Server Error: /api/loans/1/
Traceback (most recent call last):
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\serializers.py", line 429, in run_validation
    value = self.validate(value)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\api\serializers\loans.py", line 13, in validate
    if attrs['repayment_date'] < datetime.now().date():
KeyError: 'repayment_date'
"PATCH /api/loans/1/ HTTP/1.1" 500 117968
Internal Server Error: /api/clients/search/
Traceback (most recent call last):
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\api\views\loans.py", line 25, in search
    queryset = Clients.objects.filter(name__icontains=name)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\sql\query.py", line 1393, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\sql\query.py", line 1412, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\sql\query.py", line 1286, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\sql\query.py", line 1112, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\www.audiozw.com\Desktop\projects\loanmanagement\venv\lib\site-packages\django\db\models\sql\query.py", line 1539, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'name' into field. Choices are: address, email, first_name, id, id_number, is_active, is_verified, last_name, loan, phone_number, proof_of_address, proof_of_id
"GET /api/clients/search/?name=clei&id_number HTTP/1.1" 500 139894
Bad Request: /api/clients/
"POST /api/clients/ HTTP/1.1" 400 53
Bad Request: /api/clients/
"POST /api/clients/ HTTP/1.1" 400 25
Bad Request: /api/clients/
"POST /api/clients/ HTTP/1.1" 400 25
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2222
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2222
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2222
